// <auto-generated />
namespace RgbLedMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dbdegisiklik6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbdegisiklik6));
        
        string IMigrationMetadata.Id
        {
            get { return "201808181414353_db-degisiklik6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
